### PR TITLE
Login and Getter endpoints for user groups and group cards

### PR DESCRIPTION
**Pull request by Claudiohbsantos**

### CODE REVIEW

**Review by BAlexanderNance — APPROVED** [review]
Comprehensive DB/Server overhaul!
Looks good

**Review by choyeewinag — COMMENTED** [review]
Looks good!

**Review by choyeewinag — APPROVED** [review]
Looks good!

**Review by waye-huang — COMMENTED** [review]
Review Complete!

**Review by waye-huang — COMMENTED** [review]
Review Checked!

**Pull request merged**
